data: 
  batch_size: 2
  max_feat_num: 1024
  init: deg

sde:
  x: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
  adj: 
    type: VP
    beta_min: 0.2
    beta_max: 0.8
    num_scales: 1000

model:
  x: ScoreNetworkX
  adj: ScoreNetworkA_eigen
  depth: 5
  nhid: 32

train:
  num_epochs: 400
  reduce_mean: True
  lr: 1.0e-4
  lr_schedule: True
  ema: 0.999
  weight_decay: 0
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 1.0e-5

sampler:
  predictor: Euler
  corrector: Langevin
  snr: 0.1
  scale_eps: 0.7
  n_steps: 1

sample:
  use_ema: True
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 13
